<?php
require_once '../config.php';
check_login();

if ($_SESSION['role'] != 'staff') {
    redirect('../login.php');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generate Report - Staff</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/css/style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
     <style>
        @media print {
            .sidebar, .no-print { display: none !important; }
            .content { margin: 0 !important; width: 100% !important; }
        }
    </style>
</head>
<body>

<div class="d-flex">
    <div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-white no-print" style="width: 250px;">
        <a href="dashboard.php" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-4">Staff Panel</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li><a href="dashboard.php" class="nav-link text-white"><i class="fas fa-home me-2"></i> Dashboard</a></li>
            <li><a href="manage_activities.php" class="nav-link text-white"><i class="fas fa-calendar-alt me-2"></i> Activities</a></li>
            <li><a href="health_records.php" class="nav-link text-white"><i class="fas fa-heartbeat me-2"></i> Health Records</a></li>
             <li><a href="emergency.php" class="nav-link text-white"><i class="fas fa-exclamation-triangle me-2"></i> Emergency</a></li>
        </ul>
    </div>

    <div class="flex-grow-1 p-4 bg-light content">
        <div class="no-print mb-4">
             <h2>Generate Health Report</h2>
             <form method="GET" class="d-flex gap-2">
                 <select name="elderly_id" class="form-select w-50" required>
                    <option value="">Select Elderly Member...</option>
                    <?php
                    $res = mysqli_query($conn, "SELECT id, name FROM elderly_members");
                    while($row = mysqli_fetch_assoc($res)) {
                        $selected = (isset($_GET['elderly_id']) && $_GET['elderly_id'] == $row['id']) ? 'selected' : '';
                        echo "<option value='{$row['id']}' $selected>{$row['name']}</option>";
                    }
                    ?>
                </select>
                <button type="submit" class="btn btn-primary">Generate</button>
             </form>
        </div>

        <?php if (isset($_GET['elderly_id'])): 
            $eid = intval($_GET['elderly_id']);
            $elderly = mysqli_fetch_assoc(mysqli_query($conn, "SELECT * FROM elderly_members WHERE id=$eid"));
            if ($elderly):
        ?>
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="mb-0">Health Report: <?php echo $elderly['name']; ?></h3>
                    <button onclick="window.print()" class="btn btn-secondary btn-sm no-print"><i class="fas fa-print"></i> Print</button>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-6">
                            <p><strong>Date of Birth:</strong> <?php echo $elderly['dob']; ?></p>
                            <p><strong>Gender:</strong> <?php echo $elderly['gender']; ?></p>
                            <p><strong>Room No:</strong> <?php echo $elderly['room_no']; ?></p>
                        </div>
                        <div class="col-6">
                            <p><strong>Admission Date:</strong> <?php echo $elderly['admission_date']; ?></p>
                            <p><strong>Report Date:</strong> <?php echo date('Y-m-d'); ?></p>
                            <p><strong>Generated By:</strong> <?php echo $_SESSION['name']; ?></p>
                        </div>
                    </div>
                    
                    <h4 class="mt-4 border-bottom pb-2">Medical History Summary</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Doctor</th>
                                <th>Diagnosis</th>
                                <th>Prescribed Medication</th>
                                <th>Notes</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $recs = mysqli_query($conn, "SELECT * FROM medical_records WHERE elderly_id=$eid ORDER BY checkup_date DESC");
                            if (mysqli_num_rows($recs) > 0) {
                                while($r = mysqli_fetch_assoc($recs)) {
                                    echo "<tr>";
                                    echo "<td>{$r['checkup_date']}</td>";
                                    echo "<td>{$r['doctor_name']}</td>";
                                    echo "<td>{$r['diagnosis']}</td>";
                                    echo "<td>{$r['medications']}</td>";
                                    echo "<td>{$r['notes']}</td>";
                                    echo "</tr>";
                                }
                            } else {
                                echo "<tr><td colspan='5' class='text-center'>No records found</td></tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                    
                    <h4 class="mt-4 border-bottom pb-2">Additional Notes</h4>
                    <p class="text-muted border p-3" style="min-height: 100px;">
                        <!-- Space for handwritten notes if printed -->
                        (Remarks)
                    </p>
                </div>
            </div>
        <?php else: ?>
            <div class="alert alert-warning">Member not found.</div>
        <?php endif; endif; ?>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
